name: apiremates-dev
services:
    apiremates:
        container_name: apiremates-dev
        ports:
            - 5097:5096
        environment:
            - ASPNETCORE_ENVIRONMENT=$DEV_ASPNETCORE_ENVIRONMENT
            - ConnectionStrings__DbContext=$DEV_ConnectionStrings__DbContext
            - JwtSettings__Secret=$DEV_JwtSettings__Secret
            - JwtSettings__Issuer=$DEV_JwtSettings__Issuer
            - JwtSettings__Audience=$DEV_JwtSettings__Audience
            - ApiKeyCL=$DEV_ApiKeyCL
            - ExpiryMinutes=$DEV_ExpiryMinutes
            - BaseUrl=$DEV_BaseUrl
            - ApiKeyGoogleCalendar=$DEV_ApiKeyGoogleCalendar
            - RegionalCalendarId=$DEV_RegionalCalendarId
            - ClAuctionApi__Endpoint=$DEV_ClAuctionApi__Endpoint
            - ClAuctionApi__ApiKey=$DEV_ClAuctionApi__ApiKey
            - ClAuctionApi__BearerToken=$DEV_ClAuctionApi__BearerToken
        volumes:
         - ./opt/ecocircular/dev_data:/app/data
         - ./var/log/ecocircular/dev:/app/logs
        networks:
            - qa-network
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 2g
        image: apiremates-dev:v1
networks:
    qa-network:
        external: true
        name: qa-network
