name: apiremates-prod
services:
    apiremates:
        container_name: apiremates-prod
        ports:
            - 5098:5096
        environment:
            - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
            - ConnectionStrings__DbContext=$ConnectionStrings__DbContext
            - Jwt__Secret=$Jwt__Secret
            - Jwt__Issuer=$Jwt__Issuer
            - Jwt__Audience=$Jwt__Audience
            - Jwt__AccessTokenExpireMinutes=$Jwt__AccessTokenExpireMinutes
            - Jwt__RefreshTokenExpireDays=$Jwt__RefreshTokenExpireDays
            - ApiKeyCL=$ApiKeyCL
            - ExpiryMinutes=$ExpiryMinutes
            - BaseUrl=$BaseUrl
            - ApiKeyGoogleCalendar=$ApiKeyGoogleCalendar
            - RegionalCalendarId=$RegionalCalendarId
            - ClAuctionApi__Endpoint=$ClAuctionApi__Endpoint
            - ClAuctionApi__ApiKey=$ClAuctionApi__ApiKey
            - ClAuctionApi__BearerToken=$ClAuctionApi__BearerToken

        volumes:
            - ./opt/ecocircular/prod_data:/app/data
            - ./var/log/ecocircular/prod:/app/logs
        networks:
            - qa-network
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 2g
        image: apiremates-prod:v1
networks:
    qa-network:
        external: true
        name: qa-network

