name: apiremates-dev

services:
  apiremates:
    container_name: apiremates-dev
    image: apiremates-dev:v1
    
    # Carga el archivo .env desde la subcarpeta del proyecto
    env_file:
      - ./DICREP.EcommerceSubastas.API/.env
    
    ports:
      - 5097:5096
    
    environment:
      # Mapea las variables del .env (que tienen prefijo DEV_) a las variables que espera la app
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DbContext=${ConnectionStrings__DbContext}
      - Jwt__Secret=${Jwt__Secret}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__AccessTokenExpireMinutes=${Jwt__AccessTokenExpireMinutes}
      - Jwt__RefreshTokenExpireDays=${Jwt__RefreshTokenExpireDays}
      - ApiKeyCL=${ApiKeyCL}
      - ExpiryMinutes=${ExpiryMinutes}
      - BaseUrl=${BaseUrl}
      - ApiKeyGoogleCalendar=${ApiKeyGoogleCalendar}
      - RegionalCalendarId=${RegionalCalendarId}
      - ClAuctionApi__Endpoint=${ClAuctionApi__Endpoint}
      - ClAuctionApi__ApiKey=${ClAuctionApi__ApiKey}
      - ClAuctionApi__BearerToken=${ClAuctionApi__BearerToken}
    
    volumes:
      - ./opt/ecocircular/dev_data:/app/data
      - ./var/log/ecocircular/dev:/app/logs
    
    networks:
      - qa-network
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
