name: apiremates-staging
services:
    apiremates:
        container_name: apiremates-staging
        ports:
            - 5099:5096
        environment:
            - ASPNETCORE_ENVIRONMENT=$STAGING_ASPNETCORE_ENVIRONMENT
            - ConnectionStrings__DbContext=$STAGING_ConnectionStrings__DbContext
            - JwtSettings__Secret=$STAGING_JwtSettings__Secret
            - JwtSettings__Issuer=$STAGING_JwtSettings__Issuer
            - JwtSettings__Audience=$STAGING_JwtSettings__Audience
            - ApiKeyCL=$STAGING_ApiKeyCL
            - ExpiryMinutes=$STAGING_ExpiryMinutes
            - BaseUrl=$STAGING_BaseUrl
            - ApiKeyGoogleCalendar=$STAGING_ApiKeyGoogleCalendar
            - RegionalCalendarId=$STAGING_RegionalCalendarId
            - ClAuctionApi__Endpoint=$STAGING_ClAuctionApi__Endpoint
            - ClAuctionApi__ApiKey=$STAGING_ClAuctionApi__ApiKey
            - ClAuctionApi__BearerToken=$STAGING_ClAuctionApi__BearerToken
        volumes:
         - ./opt/ecocircular/staging_data:/app/data
         - ./var/log/ecocircular/staging:/app/logs
        networks:
            - qa-network
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 2g
        image: apiremates-staging:v1
networks:
    qa-network:
        external: true
        name: qa-network
